### PR TITLE
Fix memory leak in navigation service

### LINKED ISSUE #52: Fix memory leak for NavigationService
I discovered that the navigation lib has a memory leak which is already fixed in the mapbox implementation: 
https://github.com/mapbox/mapbox-navigation-android/issues/275

I think it would be a good idea to adapt those changes to fix the leak. 

I would be up to implement the changes.  
What do you think? Any thoughts why we should not adapt to the new/fixed NavigationService implementation?

### PR DESCRIPTION
**Pull request by skienzl**
This PR closes #52

### CODE REVIEW

**Comment by boldtrn** [comment]
Thanks for working on this 👍. You linked a PR from Mapbox that was included already when this repo was forked. The change you implemented here is also different to the changes that were made upstream.  All of this is perfectly fine.

I did a bit more digging around and it seems that this memory leak is a well known issue for Android and [around for many years](https://issuetracker.google.com/issues/36913703).

It is really interesting that the [Android documentation](https://developer.android.com/guide/components/bound-services#Binder) actually recommends to implement it this way.

Is it possible that there are downsides when we use the updated code you provided? Could there be issues due to using WeakReference?
Would it help to move the binder out of the Service?

Could you provide a way to reproduce the leak on main? To verify the PR fixes this?

File: libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationService.java [hunk 1]
```diff
@@ -134,10 +136,17 @@ private void startForegroundNotification(NavigationNotification navigationNotifi
...
-    class LocalBinder extends Binder {
+    final static class LocalBinder extends Binder {
+
+        private final WeakReference<NavigationService> serviceRef;
+
+        private LocalBinder(final NavigationService service) {
+            this.serviceRef = new WeakReference<>(service);
+        }
+
         NavigationService getService() {
```
Comment (avalanchas) [inline libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationService.java:147]: This should be annotated with `@Nullable` now. Is there any caller that could hold the binder, while the service is already dead? I would think that's totally possible. Those cases need a nullcheck then

Comment (skienzl) [reply libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationService.java:147]: Good call. I will add the annotation. 

Currently it is only used at one place inside the MapboxNavigation ServiceConnection. As far as I can tell it should not cause any trouble there since the usage of the service is check via `isServiceAvailable` each time as well.

Comment (boldtrn) [reply libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationService.java:148]: Thanks for updating this PR, even though it is unlikely, can you add a null check in MapboxNavigation where we call getService around these two lines:
```
    navigationService.startNavigation(this);
    isBound = true;
```

Maybe even setting isBound to false?

I think then this should be fine for merging.

**Comment by boldtrn** [comment]
Thanks, I verified the fix locally on my device as well, I think this is almost good to merge. If possible it would be nice if you could add the mentioned null check.

**Comment by boldtrn** [comment]
> Which do you mean?

`MapboxNavigation#onServiceConnected`, here we are getting the service and call `startNavigation` on the service, but the service could be null. I am not sure if this case could actually happen as in this case the service should be freshly created.

**Comment by skienzl** [comment]
> > Which do you mean?
> 
> `MapboxNavigation#onServiceConnected`, here we are getting the service and call `startNavigation` on the service, but the service could be null. I am not sure if this case could actually happen as in this case the service should be freshly created.

Is that even possible at that moment? Since onServiceConnected gets called when the service is connected and the binder of the service is ready. And a restart would restart the server which the system just "confirmed" as connected and ready. The documentation also mentions that the callback is never received if there is an issue with the service itself: https://developer.android.com/reference/android/content/ServiceConnection#onServiceConnected(android.content.ComponentName,%20android.os.IBinder)

**Comment by boldtrn** [comment]
I am not sure if this can happen, my thinking was, that checking it is not null makes sure it can't happen.

With services I tend to be overly cautious, as different manufacturers like to introduce their own "battery optimizations".

**Comment by skienzl** [comment]
> I am not sure if this can happen, my thinking was, that checking it is not null makes sure it can't happen.
> 
> With services I tend to be overly cautious, as different manufacturers like to introduce their own "battery optimizations".
> 
> If you believe this can't happen, I am fine with merging it as it is.

I just a bit worried if we get a wired state of we create a new service at this callback. Since we recreate a service which should be already running. Just not sure what would be the right resolution to the null state of the service at this callback. 

Yeah. Those custom battery "optimiser" make the handling those long running services quite frustrating...

**Review by boldtrn — APPROVED** [review]
LGTM, thanks!

**Comment by boldtrn** [comment]
Thank you very much for the great PR :)
